name: spaces2
description: Defining global spacing constants for building consistent and responsive apps.
version: 1.0.1
homepage: https://github.com/burhankhanzada/spaces2

topics:
  - gap
  - flexible
  - row
  - column

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0